In [ ]:
# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`



In [3]:
import numpy as np

In [71]:
#DONE -             #### 2. Create a null vector of size 10 (★☆☆)
                    #`hint: np.zeros`

import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [72]:
#DONE -            #### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
                        #`hint: array[4]`

x[4] = 5
print(x)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


In [19]:
#DONE -            #### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
                    #`hint: arange`

x = np.arange(10,50,1)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [44]:
#DONE -            #### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
                    #`hint: reshape`
    
b = np.arange(0,9,1).reshape((3,3))
print(b)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [51]:
#DONE -           #### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
                   #`hint: np.nonzero`
random_list = [1,2,0,0,4,0]
np.nonzero(random_list)

(array([0, 1, 4], dtype=int64),)

In [ ]:
#DONE -          #non_zero_elements = []

                    #non_zero_elements = [i for i in random_list if [i]!=0]
n                   #print(non_zero_elements)

In [53]:
#DONE -          #### 7. Create a 3x3 identity matrix (★☆☆)
                  #`hint: np.eye`

r = np.eye(3)
print(r)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
#DONE -          #### 8. Create a 3x3x3 array with random values (★☆☆)
                    #`hint: np.random.random`
c = np.random.random((3,3,3))
print(c)


[[[0.9117999  0.89316381 0.94889763]
  [0.25669809 0.52468272 0.55063148]
  [0.99809818 0.67598745 0.6973874 ]]

 [[0.69729575 0.28452589 0.17390492]
  [0.19112337 0.61507038 0.06371567]
  [0.61239547 0.60262896 0.22558059]]

 [[0.32301593 0.9491967  0.63963043]
  [0.73714709 0.46935964 0.14381789]
  [0.58182154 0.15819238 0.47659675]]]


In [68]:
#DONE -         #### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
                #`hint: min, max`
d = np.random.random((10,10))
print(d)

print(d.min())

print(d.max())


[[0.33559854 0.48306811 0.62156284 0.50521838 0.57245485 0.34826567
  0.6621988  0.48499164 0.59234872 0.1756178 ]
 [0.35178482 0.90443339 0.29271236 0.21898829 0.16422133 0.18697859
  0.67514656 0.56779215 0.76699914 0.74179221]
 [0.76093139 0.2262875  0.43920557 0.70227977 0.39209784 0.50645918
  0.11653944 0.69265771 0.5387464  0.25771743]
 [0.19645385 0.20214472 0.0129209  0.29344683 0.93590449 0.56817106
  0.7672353  0.09921741 0.69974294 0.39966739]
 [0.04388509 0.7385351  0.02965696 0.82649502 0.79798706 0.98217144
  0.16307764 0.10215707 0.89002831 0.56174693]
 [0.26425608 0.94042842 0.85795011 0.3332651  0.63843739 0.79960596
  0.7624676  0.90502206 0.1351823  0.09953027]
 [0.31740075 0.74244123 0.14655585 0.55801861 0.84517393 0.07446978
  0.15063199 0.23431748 0.62865259 0.83620791]
 [0.33248332 0.52037322 0.57252586 0.57560202 0.57458498 0.03137221
  0.36379305 0.04748143 0.28830322 0.88562299]
 [0.01283272 0.71655213 0.14641609 0.39232773 0.07121861 0.03860713
  0.14845659

In [117]:
#DONE          #### 10. Create a random vector of size 30 and find the mean value (★☆☆)
               #`hint: mean`
import numpy as np
x = np.random.random(30)
b = np.mean(x)
print(x)
print(b)



[0.77961485 0.01930566 0.66608534 0.68509957 0.06522063 0.57819096
 0.23316488 0.95787209 0.29403451 0.89254729 0.0361938  0.3811254
 0.29516056 0.08645675 0.27685847 0.87230632 0.39951193 0.96518905
 0.42807413 0.49453396 0.27921245 0.90612657 0.2080957  0.09902969
 0.6036971  0.77106695 0.29159394 0.57629029 0.4052199  0.0368452 ]
0.4527907973210655


In [99]:
#DONE -        #### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
                    #`hint: np.diag`

f = np.eye(5)
print(f)

np.diag(f, k)

#OR

f = np.arange(25).reshape((5,5))

np.diag(np.diag(f))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


NameError: name 'k' is not defined

In [107]:
#DONE -        #### 12. Normalize a 5x5 random matrix (★☆☆)
                #`hint: (x -mean)/std`

g = np.random.random((5,5))


gmax, gmin = g.max(), g.min()
g = (g - gmin)/(gmax - gmin)
print(g)

[[1.         0.76841525 0.80806819 0.7173297  0.15602039]
 [0.93667597 0.60221617 0.18578001 0.60280621 0.38516743]
 [0.40865313 0.13625573 0.55206749 0.55326393 0.67567112]
 [0.87920792 0.04803217 0.         0.19078973 0.46319131]
 [0.82291766 0.73702491 0.19824174 0.85484479 0.15534098]]


In [111]:
#DONE -        #### 13. How to find common values between two arrays? (★☆☆)
                #`hint: np.intersect1d`
j = np.array([1, 1, 2, 3, 4])
k = np.array([2, 1, 4, 6])
    
l = np.intersect1d(j, k)
    
print (l)


[1 2 4]


In [119]:
#DONE -        #### 14. Create a random vector of size 10 and sort it (★★☆)
                #`hint: sort`

x = np.random.random(10)
print(x)
x.sort()

print(x)

[0.99758825 0.35806068 0.32392683 0.19317051 0.13452948 0.59614725
 0.83345792 0.43258045 0.52304227 0.51186766]
[0.13452948 0.19317051 0.32392683 0.35806068 0.43258045 0.51186766
 0.52304227 0.59614725 0.83345792 0.99758825]


In [136]:
#DONE             15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
                       #`hint: argmax`

x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.16548348 0.91378915 0.18248489 0.85098871 0.66708455 0.71747375
 0.14309334 0.32855839 0.56107657 0.6970054 ]
[0.16548348 0.         0.18248489 0.85098871 0.66708455 0.71747375
 0.14309334 0.32855839 0.56107657 0.6970054 ]


In [137]:
#DONE  - NEED TO EXPLAIN TO MYSELF AGAIN                 #### 16. Subtract the mean of each row of a matrix (★★☆)
                            #`hint: mean(axis=,keepdims=)`
n = np.random.rand(4, 4)
print(n)

k = n - n.mean(axis=1, keepdims=True)
print(k)


[[0.13630982 0.33326763 0.5854842  0.73434831]
 [0.91827215 0.66324269 0.65971952 0.16908307]
 [0.33909267 0.51734795 0.59641849 0.74882211]
 [0.99608825 0.39865287 0.85596819 0.21082305]]
[[-0.31104267 -0.11408486  0.13813171  0.28699582]
 [ 0.31569279  0.06066334  0.05714016 -0.43349629]
 [-0.21132764 -0.03307235  0.04599819  0.1984018 ]
 [ 0.38070516 -0.21673022  0.2405851  -0.40456004]]


In [141]:
#DONE                    17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
#hint: np.argsort | np.argpartition`

x = np.arange(10000)
np.random.shuffle(x)
n = 5
print (x[np.argsort(x)[-n:]])



[9995 9996 9997 9998 9999]


In [176]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where
p = np.random.randint(9, size=(5,3))
print(p)



b = np.where(p > 4, p*p, p)
print (b)




[[6 6 1]
 [1 6 8]
 [1 2 7]
 [7 6 0]
 [1 3 4]]
[[36 36  1]
 [ 1 36 64]
 [ 1  2 49]
 [49 36  0]
 [ 1  3  4]]


In [169]:
p = np.random.randint(9, size=(5,3))
print(p)

p[p > 4] = 


b.reshape((5,3))
print(b)

SyntaxError: invalid syntax (1034300975.py, line 4)

In [174]:
p = np.random.randint(9, size=(5,3))
print(p)

p[p > 4] = p**2

[[5 6 8]
 [2 7 2]
 [4 5 2]
 [7 0 2]
 [7 8 6]]


TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions